spring.application.name=uber

#SQL
spring.datasource.url=jdbc:mysql://localhost:3306/uber
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secretkey=f6fwdFR$6ubh8721tRYTC3478DES#45678R!#!&YTCcs
earth.radius=6371