spring.application.name=uber

#SQL
spring.datasource.url=jdbc:mysql://localhost:3306/uber
spring.datasource.username={your_username}
spring.datasource.password={ypur_password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secretkey={your_key}
earth.radius=6371

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=uber-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

#openai
spring.ai.openai.api-key={your_key}
spring.ai.openai.chat.model=gpt-4o